In [1]:
import cv2
import os
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
from pygame import mixer
import time

pygame 2.5.0 (SDL 2.28.0, Python 3.11.1)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
mixer.init()
sound = mixer.Sound('alarm.wav')

In [3]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
model = load_model(r'C:\Users\HP\OneDrive\Desktop\Deep learning\prepared_Data\models\model.h5')

In [4]:
lbl=['Close', 'Open']

In [ ]:
path = os.getcwd()
cap = cv2.VideoCapture(0)
font = cv2.FONT_HERSHEY_COMPLEX_SMALL
score = 0

while(True):
    ret, frame = cap.read()
    height,width = frame.shape[:2]

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    faces = face_cascade.detectMultiScale(gray,minNeighbors = 3,scaleFactor = 1.1,minSize=(25,25))
    eyes = eye_cascade.detectMultiScale(gray,minNeighbors = 1,scaleFactor = 1.1)

    cv2.rectangle(frame, (0,height-50) , (200,height) , (0,0,0) , thickness=cv2.FILLED )

    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y) , (x+w,y+h) , (255,0,0) , 3 )

    for (x,y,w,h) in eyes:

        eye = frame[y:y+h,x:x+w]
        #eye = cv2.cvtColor(eye,cv2.COLOR_BGR2GRAY)
        eye = cv2.resize(eye,(80,80))
        eye = eye/255
        eye = eye.reshape(80,80,3)
        eye = np.expand_dims(eye,axis=0)
        prediction = model.predict(eye)
        print(prediction)
       #Condition for Close
        if prediction[0][0]>0.30:
            cv2.putText(frame,"Closed",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
            cv2.putText(frame,'Score:'+str(score),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
            score=score+1
            #print("Close Eyes")
            if(score > 20):
                try:
                    sound.play()
                except:  # isplaying = False
                    pass

        #Condition for Open
        elif prediction[0][1] > 0.70:
            score = score - 1
            if (score < 0):
                score = 0
            cv2.putText(frame,"Open",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
            #print("Open Eyes")
            cv2.putText(frame,'Score:'+str(score),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)

    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()


1/1 [==============================] - 2s 2s/step
[[6.6787245e-05 9.9993324e-01]]
1/1 [==============================] - 0s 44ms/step
[[0.30765373 0.69234633]]
1/1 [==============================] - 0s 40ms/step
[[3.4738023e-05 9.9996531e-01]]
1/1 [==============================] - 0s 40ms/step
[[0.00398404 0.99601597]]
1/1 [==============================] - 0s 44ms/step
[[0.3812317  0.61876833]]
1/1 [==============================] - 0s 42ms/step
[[0.02689617 0.97310376]]
1/1 [==============================] - 0s 42ms/step
[[0.5745148  0.42548522]]
1/1 [==============================] - 0s 42ms/step
[[0.10420758 0.8957924 ]]
1/1 [==============================] - 0s 42ms/step
[[0.00325259 0.9967474 ]]
1/1 [==============================] - 0s 42ms/step
[[9.785859e-04 9.990214e-01]]
1/1 [==============================] - 0s 41ms/step
[[0.350726 0.649274]]
1/1 [==============================] - 0s 38ms/step
[[0.02731421 0.9726858 ]]
1/1 [==============================] - 0s 37ms/step
[[

1/1 [==============================] - 0s 37ms/step
[[0.7721996  0.22780046]]
1/1 [==============================] - 0s 39ms/step
[[0.12517199 0.87482804]]
1/1 [==============================] - 0s 37ms/step
[[0.60344774 0.39655223]]
1/1 [==============================] - 0s 38ms/step
[[0.03103576 0.9689642 ]]
1/1 [==============================] - 0s 39ms/step
[[0.21613316 0.7838668 ]]
1/1 [==============================] - 0s 37ms/step
[[0.6934609  0.30653915]]
1/1 [==============================] - 0s 38ms/step
[[0.10656692 0.89343303]]
1/1 [==============================] - 0s 38ms/step
[[0.5716291  0.42837092]]
1/1 [==============================] - 0s 37ms/step
[[0.5807765  0.41922355]]
1/1 [==============================] - 0s 40ms/step
[[0.11005663 0.88994336]]
1/1 [==============================] - 0s 38ms/step
[[0.9871802 0.0128198]]
1/1 [==============================] - 0s 35ms/step
[[0.980718   0.01928191]]
1/1 [==============================] - 0s 37ms/step
[[0.68743837 0

1/1 [==============================] - 0s 38ms/step
[[0.59541047 0.40458956]]
1/1 [==============================] - 0s 39ms/step
[[0.01672461 0.9832755 ]]
1/1 [==============================] - 0s 38ms/step
[[0.73856956 0.2614304 ]]
1/1 [==============================] - 0s 37ms/step
[[6.295036e-04 9.993705e-01]]
1/1 [==============================] - 0s 38ms/step
[[0.71380824 0.28619173]]
1/1 [==============================] - 0s 69ms/step
[[0.03782823 0.9621718 ]]
1/1 [==============================] - 0s 49ms/step
[[0.3736681  0.62633187]]
1/1 [==============================] - 0s 43ms/step
[[0.16558251 0.8344175 ]]
1/1 [==============================] - 0s 41ms/step
[[0.9968323  0.00316771]]
1/1 [==============================] - 0s 41ms/step
[[0.273156 0.726844]]
1/1 [==============================] - 0s 41ms/step
[[0.6149441 0.3850559]]
1/1 [==============================] - 0s 40ms/step
[[0.62341934 0.37658066]]
1/1 [==============================] - 0s 55ms/step
[[0.71387035 0

1/1 [==============================] - 0s 41ms/step
[[0.6756712 0.3243288]]
1/1 [==============================] - 0s 40ms/step
[[0.9279057  0.07209434]]
1/1 [==============================] - 0s 46ms/step
[[6.760353e-05 9.999324e-01]]
1/1 [==============================] - 0s 56ms/step
[[0.0010815  0.99891853]]
1/1 [==============================] - 0s 59ms/step
[[0.8211252  0.17887476]]
1/1 [==============================] - 0s 48ms/step
[[0.51568836 0.4843116 ]]
1/1 [==============================] - 0s 54ms/step
[[0.09256823 0.9074318 ]]
1/1 [==============================] - 0s 52ms/step
[[0.00126978 0.99873024]]
1/1 [==============================] - 0s 47ms/step
[[0.98555136 0.01444869]]
1/1 [==============================] - 0s 58ms/step
[[1.1311901e-04 9.9988687e-01]]
1/1 [==============================] - 0s 47ms/step
[[0.8942384  0.10576165]]
1/1 [==============================] - 0s 51ms/step
[[2.7677532e-07 9.9999976e-01]]
1/1 [==============================] - 0s 45ms/ste

###### 